-- ============================================================
-- Tech Solution Pakistan — COMPLETE Supabase Schema v3
-- ============================================================
-- HOW TO USE:
--   Supabase Dashboard → SQL Editor → New query → paste → Run
--   Safe to run on FRESH or EXISTING database (fully idempotent)
-- ============================================================

-- ============================================================
-- 1. HELPER FUNCTION — is_admin()
-- ============================================================
create or replace function public.is_admin()
returns boolean
language sql stable
security definer set search_path = public
as $$
  select exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  );
$$;

-- ============================================================
-- 2. PROFILES  (one row per auth user, auto-created on signup)
-- ============================================================
create table if not exists public.profiles (
  id         uuid        primary key references auth.users(id) on delete cascade,
  name       text        not null default '',
  email      text        not null default '',
  company    text,
  phone      text,
  role       text        not null default 'client'
                         check (role in ('client', 'admin', 'expert')),
  created_at timestamptz not null default now()
);

-- Auto-create profile row whenever a new user signs up
create or replace function public.handle_new_user()
returns trigger language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, name, email, company, phone, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'name', ''),
    coalesce(new.email, ''),
    new.raw_user_meta_data->>'company',
    new.raw_user_meta_data->>'phone',
    case when lower(coalesce(new.email, '')) = 'muzzammilkhan7890@gmail.com'
         then 'admin' else 'client' end
  )
  on conflict (id) do update
    set role = case when lower(coalesce(new.email, '')) = 'muzzammilkhan7890@gmail.com'
                    then 'admin' else public.profiles.role end;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Backfill profiles for any EXISTING auth users (signed up before the
-- trigger, or after a reset), then guarantee the owner is an admin.
insert into public.profiles (id, name, email)
select u.id, coalesce(u.raw_user_meta_data->>'name', ''), coalesce(u.email, '')
from auth.users u
on conflict (id) do nothing;

update public.profiles set role = 'admin'
where lower(email) = 'muzzammilkhan7890@gmail.com';

-- ============================================================
-- 3. ORDERS  (client project requests)
-- ============================================================
create table if not exists public.orders (
  id               bigint      generated always as identity primary key,
  user_id          uuid        not null references auth.users(id) on delete cascade,

  -- project basics
  service          text        not null,
  description      text,
  budget           numeric     not null default 0,
  deadline         text,
  priority         text        not null default 'medium'
                               check (priority in ('low', 'medium', 'high')),
  status           text        not null default 'pending'
                               check (status in (
                                 'pending','approved','in_progress',
                                 'delivered','completed','rejected'
                               )),

  -- finance estimates (auto-calculated on insert)
  est_cost         numeric     not null default 0,
  est_profit       numeric     not null default 0,
  breakdown        jsonb,

  -- client-supplied file links
  file_link        text,
  file_link_type   text        check (file_link_type in ('gdrive', 'github')),

  -- delivery
  delivery_type    text        check (delivery_type in ('github', 'gdrive', 'other')),
  delivery_url     text,
  delivered_at     timestamptz,

  -- payment tracking
  payment_status   text        not null default 'unpaid'
                               check (payment_status in ('unpaid', 'paid')),
  paid_at          timestamptz,
  paid_marked_by   text        check (paid_marked_by in ('client', 'admin')),

  -- serial number (auto-generated by trigger: TSP-YYYYMM-XXXX)
  order_serial     text,

  -- optional admin-supplied client details (for manual/offline clients)
  client_name      text,
  client_email     text,
  client_phone     text,
  client_company   text,

  created_at       timestamptz not null default now()
);

-- Serial number generator: TSP-202506-0001
create or replace function public.generate_order_serial(order_id bigint, created timestamptz)
returns text language sql immutable as $$
  select 'TSP-' || to_char(created, 'YYYYMM') || '-' || lpad(order_id::text, 4, '0')
$$;

create or replace function public.set_order_serial()
returns trigger language plpgsql as $$
begin
  new.order_serial := public.generate_order_serial(new.id, new.created_at);
  return new;
end;
$$;

drop trigger if exists trg_set_order_serial on public.orders;
create trigger trg_set_order_serial
  before insert on public.orders
  for each row execute function public.set_order_serial();

-- Backfill any existing rows that don't yet have a serial
update public.orders
set order_serial = public.generate_order_serial(id, created_at)
where order_serial is null;

-- ============================================================
-- 4. MEETINGS
-- ============================================================
create table if not exists public.meetings (
  id         bigint      generated always as identity primary key,
  user_id    uuid        not null references auth.users(id) on delete cascade,
  order_id   bigint      references public.orders(id) on delete set null,
  title      text        not null,
  date       date        not null,
  time       text        not null,
  duration   text        not null default '30m',
  timezone   text        not null default 'Asia/Karachi',
  status     text        not null default 'requested'
                         check (status in ('requested', 'confirmed', 'cancelled')),
  -- optional: admin-supplied client name for display
  client_name text,
  created_at timestamptz not null default now()
);

-- ============================================================
-- 5. CLIENTS  (admin-managed directory — no login required)
-- ============================================================
create table if not exists public.clients (
  id         bigint      generated always as identity primary key,
  name       text        not null,
  email      text,
  phone      text,
  company    text,
  notes      text,
  user_id    uuid        references auth.users(id) on delete set null,
  created_by uuid        references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

-- ============================================================
-- 6. EXPERTS  (team members who receive tasks)
-- ============================================================
create table if not exists public.experts (
  id           bigint      generated always as identity primary key,
  user_id      uuid        references auth.users(id) on delete set null,
  name         text        not null,
  title        text        not null default 'Specialist',
  bio          text,
  skills       text[]      not null default '{}',
  accent       text        not null default 'purple',
  show_on_hero boolean     not null default true,
  active       boolean     not null default true,
  avatar_url   text,
  created_at   timestamptz not null default now()
);

-- ============================================================
-- 7. TASKS  (admin assigns to experts, linked to orders)
-- ============================================================
create table if not exists public.tasks (
  id            bigint      generated always as identity primary key,
  expert_id     bigint      not null references public.experts(id) on delete cascade,
  title         text        not null,
  description   text,
  service       text,
  client_alias  text,           -- label shown to expert (hides real client name)
  expert_budget numeric     not null default 0,
  status        text        not null default 'assigned'
                            check (status in (
                              'assigned','in_progress','submitted','approved','completed'
                            )),
  due_date      date,

  -- link to the client order
  order_serial  text,           -- e.g. TSP-202506-0001
  order_id      bigint      references public.orders(id) on delete set null,

  created_at    timestamptz not null default now()
);

-- task_finance: admin-only financial data hidden from experts via RLS
create table if not exists public.task_finance (
  task_id       bigint      primary key references public.tasks(id) on delete cascade,
  client_budget numeric     not null default 0,
  profit        numeric     generated always as (client_budget - (
    select expert_budget from public.tasks t where t.id = task_id
  )) stored,
  order_serial  text,
  created_at    timestamptz not null default now()
);

-- ============================================================
-- 8. MESSAGES  (AI assistant chat history, per user)
-- ============================================================
create table if not exists public.messages (
  id         bigint      generated always as identity primary key,
  user_id    uuid        not null references auth.users(id) on delete cascade,
  role       text        not null check (role in ('user', 'assistant')),
  content    text        not null,
  created_at timestamptz not null default now()
);

-- ============================================================
-- 9. CHAT MESSAGES  (live client ↔ admin real-time chat)
-- ============================================================
create table if not exists public.chat_messages (
  id          bigint      generated always as identity primary key,
  room_id     uuid        not null,  -- equals the client's user_id (one room per client)
  sender_id   uuid        not null references auth.users(id) on delete cascade,
  sender_role text        not null check (sender_role in ('client', 'admin')),
  content     text        not null,
  read_at     timestamptz,           -- null = unread by the other party
  created_at  timestamptz not null default now()
);

create index if not exists chat_messages_room_idx
  on public.chat_messages(room_id, created_at);

-- ============================================================
-- 10. ONLINE PRESENCE  (heartbeat — upserted every ~20 s)
-- ============================================================
create table if not exists public.online_presence (
  user_id   uuid        primary key references auth.users(id) on delete cascade,
  role      text        not null default 'client',
  last_seen timestamptz not null default now()
);

-- ============================================================
-- 11. ROW-LEVEL SECURITY
-- ============================================================
alter table public.profiles        enable row level security;
alter table public.orders          enable row level security;
alter table public.meetings        enable row level security;
alter table public.clients         enable row level security;
alter table public.experts         enable row level security;
alter table public.tasks           enable row level security;
alter table public.task_finance    enable row level security;
alter table public.messages        enable row level security;
alter table public.chat_messages   enable row level security;
alter table public.online_presence enable row level security;

-- ── PROFILES ──────────────────────────────────────────────────────────────
drop policy if exists "profiles self read"    on public.profiles;
drop policy if exists "profiles expert read"  on public.profiles;
drop policy if exists "profiles self update"  on public.profiles;
drop policy if exists "profiles admin update" on public.profiles;

create policy "profiles self read" on public.profiles
  for select using (
    id = auth.uid()
    or public.is_admin()
    or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'expert')
  );

create policy "profiles self update" on public.profiles
  for update using (id = auth.uid() or public.is_admin());

-- ── ORDERS ────────────────────────────────────────────────────────────────
drop policy if exists "orders read"   on public.orders;
drop policy if exists "orders insert" on public.orders;
drop policy if exists "orders update" on public.orders;

create policy "orders read" on public.orders
  for select using (user_id = auth.uid() or public.is_admin());

create policy "orders insert" on public.orders
  for insert with check (user_id = auth.uid());

create policy "orders update" on public.orders
  for update using (user_id = auth.uid() or public.is_admin());

-- ── MEETINGS ──────────────────────────────────────────────────────────────
drop policy if exists "meetings read"   on public.meetings;
drop policy if exists "meetings insert" on public.meetings;
drop policy if exists "meetings update" on public.meetings;

create policy "meetings read" on public.meetings
  for select using (user_id = auth.uid() or public.is_admin());

create policy "meetings insert" on public.meetings
  for insert with check (user_id = auth.uid());

create policy "meetings update" on public.meetings
  for update using (user_id = auth.uid() or public.is_admin());

-- ── CLIENTS (admin directory) ─────────────────────────────────────────────
drop policy if exists "clients admin all" on public.clients;

create policy "clients admin all" on public.clients
  for all using (public.is_admin()) with check (public.is_admin());

-- ── EXPERTS ───────────────────────────────────────────────────────────────
drop policy if exists "experts public read"  on public.experts;
drop policy if exists "experts admin all"    on public.experts;
drop policy if exists "experts self update"  on public.experts;

create policy "experts public read" on public.experts
  for select using (true);

create policy "experts admin all" on public.experts
  for all using (public.is_admin()) with check (public.is_admin());

create policy "experts self update" on public.experts
  for update using (user_id = auth.uid());

-- ── TASKS ─────────────────────────────────────────────────────────────────
drop policy if exists "tasks expert read"  on public.tasks;
drop policy if exists "tasks admin all"    on public.tasks;
drop policy if exists "tasks expert update" on public.tasks;

-- Experts can only see their own tasks
create policy "tasks expert read" on public.tasks
  for select using (
    public.is_admin()
    or exists (
      select 1 from public.experts e
      where e.id = tasks.expert_id and e.user_id = auth.uid()
    )
  );

create policy "tasks admin all" on public.tasks
  for all using (public.is_admin()) with check (public.is_admin());

create policy "tasks expert update" on public.tasks
  for update using (
    exists (
      select 1 from public.experts e
      where e.id = tasks.expert_id and e.user_id = auth.uid()
    )
  );

-- ── TASK FINANCE (admin-only — hidden from experts) ───────────────────────
drop policy if exists "task_finance admin only" on public.task_finance;

create policy "task_finance admin only" on public.task_finance
  for all using (public.is_admin()) with check (public.is_admin());

-- ── MESSAGES (AI assistant) ───────────────────────────────────────────────
drop policy if exists "messages read"   on public.messages;
drop policy if exists "messages insert" on public.messages;

create policy "messages read" on public.messages
  for select using (user_id = auth.uid() or public.is_admin());

create policy "messages insert" on public.messages
  for insert with check (user_id = auth.uid());

-- ── CHAT MESSAGES (live chat) ─────────────────────────────────────────────
drop policy if exists "chat read own room"   on public.chat_messages;
drop policy if exists "chat insert own room" on public.chat_messages;
drop policy if exists "chat update read_at"  on public.chat_messages;

create policy "chat read own room" on public.chat_messages
  for select using (room_id = auth.uid() or public.is_admin());

create policy "chat insert own room" on public.chat_messages
  for insert with check (
    sender_id = auth.uid()
    and (room_id = auth.uid() or public.is_admin())
  );

create policy "chat update read_at" on public.chat_messages
  for update using (room_id = auth.uid() or public.is_admin());

-- ── ONLINE PRESENCE ───────────────────────────────────────────────────────
drop policy if exists "presence read all"   on public.online_presence;
drop policy if exists "presence upsert own" on public.online_presence;

create policy "presence read all" on public.online_presence
  for select using (true);

create policy "presence upsert own" on public.online_presence
  for all using (user_id = auth.uid());

-- ============================================================
-- 12. REALTIME  (enable live subscriptions)
-- ============================================================
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and tablename = 'chat_messages'
  ) then
    alter publication supabase_realtime add table public.chat_messages;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and tablename = 'online_presence'
  ) then
    alter publication supabase_realtime add table public.online_presence;
  end if;
end $$;

-- ============================================================
-- 13. QUICK REFERENCE
-- ============================================================
-- After your first sign-up, grant yourself admin:
--   update public.profiles set role = 'admin' where email = 'you@example.com';
--
-- Grant expert role to a team member:
--   update public.profiles set role = 'expert' where email = 'expert@example.com';
--
-- TABLE SUMMARY
-- ┌─────────────────┬────────────────────────────────────────────────────────┐
-- │ profiles        │ one row per auth user · roles: client | admin | expert │
-- │ orders          │ client project requests · auto serial TSP-YYYYMM-XXXX  │
-- │ meetings        │ meeting requests (date, time, duration, status)         │
-- │ clients         │ admin-managed directory (no login needed)               │
-- │ experts         │ team members shown on hero + task recipients            │
-- │ tasks           │ tasks assigned to experts · linked via order_serial     │
-- │ task_finance    │ admin-only: client budget + profit (hidden from expert) │
-- │ messages        │ AI assistant history per user                           │
-- │ chat_messages   │ live client↔admin chat (room_id = client user_id)      │
-- │ online_presence │ heartbeat for online/offline status (~45 s TTL)        │
-- └─────────────────┴────────────────────────────────────────────────────────┘
-- ============================================================
